#!/usr/bin/env ruby
#-------------------------------------------------------------------------------------------------------------
#  Sifttter Redux
#
#  A modification of Craig Eley's Sifttter that allows for smart installation on a standalone *NIX
#  device (such as a Raspberry Pi).
#
#  Sifttter copyright Craig Eley 2014 <http://craigeley.com>
#
#  Copyright (c) 2014
#  Aaron Bach <bachya1208@gmail.com>
#  
#  Permission is hereby granted, free of charge, to any person
#  obtaining a copy of this software and associated documentation
#  files (the "Software"), to deal in the Software without
#  restriction, including without limitation the rights to use,
#  copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the
#  Software is furnished to do so, subject to the following
#  conditions:
#  
#  The above copyright notice and this permission notice shall be
#  included in all copies or substantial portions of the Software.
#  
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
#  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
#  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
#  OTHER DEALINGS IN THE SOFTWARE.
#-------------------------------------------------------------------------------------------------------------

# Gems
require 'chronic'
require 'fileutils'
require 'gli'
require 'time'

# Sifttter Redux classes and Modules
require File.join(File.dirname(__FILE__), 'lib/ConfigManagerClass.rb')
require File.join(File.dirname(__FILE__), 'lib/CliManagerModule.rb')
require File.join(File.dirname(__FILE__), 'lib/OsModule.rb')

#|  ======================================================
#|  CONSTANTS
#|
#|  Don't change these unless you really know
#|  what you're doing.
#|  ======================================================

# Sifttter and Sifttter Redux Constants
SRD_CONFIG_FILEPATH = File.join(ENV['HOME'], '.sifttter_redux')
SFT_LOCAL_FILEPATH = "/tmp/sifttter"
SFT_REMOTE_FILEPATH = "/Apps/ifttt/sifttter"

# Dropbox Upload Constants
DBU_LOCAL_FILEPATH = "/usr/local/opt"

# Day One Constants
DO_REMOTE_FILEPATH = "/Apps/Day\\ One/Journal.dayone/entries"
DO_LOCAL_FILEPATH = "/tmp/dayone"

# Miscellaneous Constants
VERSION = 1.3

#|  ------------------------------------------------------
#|  collect_preferences method
#|
#|  Collects preferences from the user and stores the
#|  entered values into a configuration file.
#|  @return Void
#|  ------------------------------------------------------
def collect_preferences
  CliMessage.section('COLLECTING PREFERENCES...')
  
  pref = CliMessage.prompt("Location for downloaded Sifttter files from Dropbox", SFT_LOCAL_FILEPATH)
  $config.add_to_section({"sifttter_local_filepath" => pref}, "sifttter_redux")
  
  pref = CliMessage.prompt("Location of Sifttter files in Dropbox", SFT_REMOTE_FILEPATH)
  $config.add_to_section({"sifttter_remote_filepath" => pref}, "sifttter_redux")
  
  pref = CliMessage.prompt("Location for downloaded Day One files from Dropbox", DO_LOCAL_FILEPATH)
  $config.add_to_section({"dayone_local_filepath" => pref}, "sifttter_redux")
  
  pref = CliMessage.prompt("Location of Day One files in Dropbox", DO_REMOTE_FILEPATH)
  $config.add_to_section({"dayone_remote_filepath" => pref}, "sifttter_redux")
end

#|  ------------------------------------------------------
#|  download_sifttter_files method
#|
#|  Downloads Sifttter files from Dropbox
#|  @return Void
#|  ------------------------------------------------------
def download_sifttter_files
  # Download all Sifttter files from Dropbox.
  CliMessage.info('Downloading Sifttter files...', false)
  output = `#{$db_uploader} download #{$config.sifttter_redux["sifttter_remote_filepath"]} #{$config.sifttter_redux["sifttter_local_filepath"]}`
  CliMessage.finish_message('DONE.')
end

#|  ------------------------------------------------------
#|  initialize_procedures method
#|
#|  Initializes Sifttter Redux by downloading and collecting
#|  all necessary items and info.
#|  @return Void
#|  ------------------------------------------------------
def initialize_procedures
  $config.reset
  $config.create_section("sifttter_redux")
  $config.add_to_section({"config_location" => $config.configFile}, "sifttter_redux")
  
  install_db_uploader 
  collect_preferences
  
  CliMessage.section("INITIALIZATION COMPLETE!")
  
  $config.save_configuration
end

#|  ------------------------------------------------------
#|  install_db_uploader method
#|
#|  Installs Dropbox Uploader to a user-specified location
#|  by cloning the git repository.
#|  @return Void
#|  ------------------------------------------------------
def install_db_uploader
  valid_directory_chosen = false
  
  CliMessage.section('DOWNLOADING DROPBOX UPLOADER...')
  
  # Create a new configuration section for Dropbox-Uploader
  $config.create_section("db_uploader")
  
  until valid_directory_chosen
    # Prompt the user for a location to save Dropbox Uploader. "
    db_uploader_location = CliMessage.prompt("Location for Dropbox-Uploader", DBU_LOCAL_FILEPATH)
    db_uploader_location.chop! if db_uploader_location.end_with?('/')
    db_uploader_location = "/usr/local/opt" if db_uploader_location.empty?
    
    # If the entered directory exists, clone the repository.
    if File.directory?(db_uploader_location)
      valid_directory_chosen = true
      db_uploader_location << "/Dropbox-Uploader"
      
      # If, for some reason, Dropbox Uploader alread exists at this location,
      # skip the clone.
      if File.directory?(db_uploader_location)
        CliMessage.info("You seem to already have Dropbox Uploader at this location; skipping...")
      else
        %x{git clone https://github.com/andreafabrizi/Dropbox-Uploader.git #{db_uploader_location}}
      end
      
      # Save config data to YAML.
      $config.add_to_section({"local_filepath" => db_uploader_location}, "db_uploader")
    else
      puts "Sorry, but #{db_uploader_location} isn't a valid directory."
    end
  end
end

#|  ------------------------------------------------------
#|  run_sifttter method
#|
#|  Modified form of Sifttter
#| 
#|  Sifttter: An IFTTT-to-Day One Logger by Craig Eley 2014
#|  Based on tp-dailylog.rb by Brett Terpstra 2012
#|  @param date The date to use when scanning Sifttter files
#|  @return Void
#|  ------------------------------------------------------
def run_sifttter(date)
  uuid_command = "uuidgen" if OS.mac?
  uuid_command = "uuid" if OS.linux?
  uuid = %x{#{uuid_command}}.gsub(/-/,'').strip 
  
  date_for_title = date.strftime('%B %d, %Y')
  datestamp = date.to_time.utc.iso8601
  starred = false

  template = ERB.new <<-XMLTEMPLATE
  <?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
  <dict>
  	<key>Creation Date</key>
  	<date><%= datestamp %></date>
  	<key>Entry Text</key>
  	<string><%= entrytext %></string>
  	<key>Starred</key>
  	<<%= starred %>/>
  	<key>Tags</key>
  	<array>
  		<string>daily logs</string>
  	</array>
  	<key>UUID</key>
  	<string><%= uuid %></string>
  </dict>
  </plist>
  XMLTEMPLATE

  date_regex = "#{date.strftime('%B')} 0?#{date.strftime('%-d')}, #{date.strftime('%Y')}"
  time_regex = "\d{1,2}:\d{1,2}\s?[AaPpMm]{2}"

  files = %x{find #{$config.sifttter_redux["sifttter_local_filepath"]} -type f -name '*.txt' | grep -v -i daily | sort}

  projects = []
  files.split("\n").each do |file|
  	if File.exists?(file.strip)
  		f = File.open(file.strip, encoding: 'UTF-8')
  		lines = f.read
  		f.close
  		project = "### " + File.basename(file).gsub(/^.*?\/([^\/]+)$/,"\\1") + "\n"

  		found_completed = false
  		lines.each_line do |line|
  			if line =~ /&/
  				line.gsub!(/[&]/, 'and')
  			end
  			if line =~ /#{date_regex}/
  				found_completed = true
  				project += line.gsub(/@done/,'').gsub(/#{date_regex}\s(-|at)\s/, '').gsub(/#{time_regex}\s-\s/, '').strip + "\n"
  			end
  		end
  	end
  	if found_completed
  		projects.push(project)
  	end
  end
  
  if projects.length <=0
  	abort "No entries found"
  end

  if projects.length > 0  
  	entrytext = "# Things done on #{date_for_title}\n\n"
  	projects.each do |project|
  		entrytext += project.gsub(/.txt/, ' ') + "\n\n"
  	end
    
    Dir.mkdir($config.sifttter_redux["dayone_local_filepath"]) if !Dir.exists?($config.sifttter_redux["dayone_local_filepath"])
    
  	fh = File.new(File.expand_path($config.sifttter_redux["dayone_local_filepath"] + "/" + uuid + ".doentry"), 'w+')
  	fh.puts template.result(binding)
  	fh.close
  	puts "Entry logged for #{date_for_title}"
  end
end

#|  ======================================================
#|  Main Program
#|
#|  Bootstraps the CLI and guides the user through use.
#|  ======================================================
include GLI::App
$config = ConfigManager.instance

# Set the description as it will be displayed in the help message
program_desc "Sifttter Redux v#{VERSION}

    A modification of Craig Eley's Sifttter that allows for smart
    installation on a standalone *NIX device (such as a Raspberry Pi)."

#|  ------------------------------------------------------
#|  exec command
#|
#|  Executes the script.
#|  ------------------------------------------------------
pre do |global_options, command, options, args|
  if !File.exists?(SRD_CONFIG_FILEPATH)
    CliMessage.info("It doesn't look like you've initlized Sifttter Redux yet. Doing that now()...")
    initialize_procedures
  end

  $db_uploader = File.join($config.db_uploader["local_filepath"], "dropbox_uploader.sh")
end

desc 'Execute the script'
command :exec do |c|  
  c.flag(
    [:f, :from],
    :desc => 'Run catch-up mode with this start date',
  )
  
  c.flag(
    [:t, :to],
    :desc => 'Run catch-up mode with this end date (must be accompanied by --from)',
  )
  
  c.switch(
    [:c, :current_week],
    :desc => 'Run catch-up mode for the last 7 days'
  )
  
  c.switch(
    [:i, :include_today],
    :desc => 'Include today\'s date in catch-up'
  )
  
  c.switch(
    [:y, :yesterday],
    :desc => 'Run catch-up mode for yesterday'
  )
  
  c.action do |global_options, options, args|
    CliMessage.section('EXECUTING...')
    
    # In this case, the user has attempted to specify some sort of catch-up.
    if (options[:c] || options[:y] || options[:f] || options[:t])
      
      # "Previous 7 days" catch-up
      if (options[:c])
        start_date = Date.today - 7
        
        if (options[:i])
          end_date = Date.today
        else
          end_date = Date.today.prev_day
        end
        
      # "Yesterday" catch-up
      elsif (options[:y])
        start_date = Date.today.prev_day
        end_date = Date.today.prev_day
        
      # "Date range" catch-up
      elsif (options[:f] || options[:t])
        _chronic_parsed_from_date = Chronic.parse(options[:f]).to_date rescue nil
        _chronic_parsed_to_date = Chronic.parse(options[:t]).to_date rescue nil
        
        if (_chronic_parsed_from_date.nil? && _chronic_parsed_to_date.nil?)
          CliMessage.error("Please ensure that you are providing valid dates...")
          exit!
        end

        if (_chronic_parsed_from_date.nil? && !_chronic_parsed_to_date.nil?)
          CliMessage.error("You can't specify -t without specifying -f...")
          exit!
        end
        
        if (!_chronic_parsed_from_date.nil? && _chronic_parsed_to_date.nil?)
          start_date = _chronic_parsed_from_date

          if (options[:i])
            end_date = Date.today
          else
            end_date = Date.today.prev_day
          end
        else
          if (_chronic_parsed_from_date.nil? || _chronic_parsed_to_date.nil?)
            CliMessage.error("Please ensure that you are providing valid dates...")
            exit!
          end
          
          if (_chronic_parsed_from_date > _chronic_parsed_to_date)
            CliMessage.error("The start date must be before or equal to the end date...")
            exit!
          end
          
          start_date = _chronic_parsed_from_date
          
          if (_chronic_parsed_to_date > Date.today)
            CliMessage.warning("Ignoring ending date greater than today and using #{Date.today}...")
            end_date = Date.today
          else
            end_date = _chronic_parsed_to_date
          end
        end
      end
    else
      start_date = Date.today
      end_date = Date.today
    end
    
    CliMessage.info("Creating entries for dates from #{start_date} to #{end_date}...")

    download_sifttter_files
    
    (start_date..end_date).each do |date|
      run_sifttter(date)
    end
    
    # Upload any Day One entries to Dropbox (if there are any).
    if (!Dir[$config.sifttter_redux["dayone_local_filepath"] + "/*"].empty?)
      CliMessage.info("Uploading Day One entries to Dropbox...", false)
      output = `#{$db_uploader} upload #{$config.sifttter_redux["dayone_local_filepath"] + "/*"} #{$config.sifttter_redux["dayone_remote_filepath"]}`
      CliMessage.finish_message('DONE.')
    end
    
    # Remove any downloaded local files that we no longer need.
    CliMessage.info("Removing downloaded Day One files...", false)
    FileUtils.rm_rf($config.sifttter_redux["dayone_local_filepath"]) if Dir.exists?($config.sifttter_redux["dayone_local_filepath"])
    CliMessage.finish_message('DONE.')
    
    CliMessage.info("Removing downloaded Sifttter files...", false)
    FileUtils.rm_rf($config.sifttter_redux["sifttter_local_filepath"]) if Dir.exists?($config.sifttter_redux["sifttter_local_filepath"])
    CliMessage.finish_message('DONE.')
      
    CliMessage.section('EXECUTION COMPLETE!')
  end
end

#|  ------------------------------------------------------
#|  init command
#|
#|  Initializes the script.
#|  ------------------------------------------------------
desc 'Install and initialize dependencies'
command :init do |c|
  c.action do |global_options, options, args|
    CliMessage.section('INITIALIZING...')

    if File.exists?($config.configFile)
      optionReinitialize = CliMessage.prompt("It looks like you've already initialized Sifttter Redux. Do you want to re-initialize?", "N").downcase
      initialize_procedures if optionReinitialize == 'y'
    else
      initialize_procedures
    end
  end
end

exit run(ARGV)